<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.3.0-preview.4</Version>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <EnablePackageValidation Condition="'$(IsPackable)' == 'true'">true</EnablePackageValidation>
    <PublicApiAnalyzerEnabled Condition="'$(IsPackable)' == 'true'">true</PublicApiAnalyzerEnabled>
    <NoWarn>$(NoWarn);RS0026;RS0027</NoWarn>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsPackable)' == 'true'">
    <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" Version="3.3.4" PrivateAssets="all" />
  </ItemGroup>

</Project>
