<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Penghou.Baize.Ollama\Penghou.Baize.Ollama.csproj" />
    <ProjectReference Include="..\..\src\Penghou.Baize.Router\Penghou.Baize.Router.csproj" />
  </ItemGroup>
</Project>
