namespace Penghou.Baize;

/// <summary>Token usage reported for a completion.</summary>
/// <param name="PromptTokens">Tokens consumed by the input prompt.</param>
/// <param name="CompletionTokens">Tokens generated by the completion.</param>
/// <param name="TotalTokens">Total tokens consumed across the call.</param>
/// <param name="PromptCacheHitTokens">Tokens served from a prompt cache, when reported.</param>
/// <param name="PromptCacheMissTokens">Tokens written to a prompt cache, when reported.</param>
/// <param name="ThinkingTokens">Tokens generated for provider-side reasoning or thinking, when reported.</param>
public sealed record LlmUsage(
    int? PromptTokens,
    int? CompletionTokens,
    int? TotalTokens,
    int? PromptCacheHitTokens = null,
    int? PromptCacheMissTokens = null,
    int? ThinkingTokens = null)
{
    /// <summary>Actual provider-reported cost, when available.</summary>
    public decimal? Cost { get; init; }

    /// <summary>Currency associated with <see cref="Cost"/>, when available.</summary>
    public string? Currency { get; init; }
}
