using System.Text.Json.Serialization;

namespace Penghou.Baize.Gemini;

/// <summary>
/// Wire model for a Gemini generateContent response (one per streamed chunk).
/// </summary>
public sealed class GeminiChatResponse
{
    /// <summary>The candidate responses generated by the model.</summary>
    [JsonPropertyName("candidates")]
    public List<GeminiCandidate>? Candidates { get; init; }

    /// <summary>Aggregate token usage for the chunk.</summary>
    [JsonPropertyName("usageMetadata")]
    public GeminiUsage? Usage { get; init; }
}

/// <summary>
/// Wire model for a single Gemini response candidate.
/// </summary>
public sealed class GeminiCandidate
{
    /// <summary>The candidate's content parts.</summary>
    [JsonPropertyName("content")]
    public GeminiContent? Content { get; init; }

    /// <summary>The finish reason, for example <c>STOP</c> or <c>MAX_OUTPUT_TOKENS</c>.</summary>
    [JsonPropertyName("finishReason")]
    public string? FinishReason { get; init; }
}

/// <summary>
/// Wire model for a Gemini candidate's content.
/// </summary>
public sealed class GeminiContent
{
    /// <summary>The content parts.</summary>
    [JsonPropertyName("parts")]
    public List<GeminiContentPart>? Parts { get; init; }
}